# -*- coding: utf-8 -*-
"""simple_prog.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z8dDN-dqf2S0SH9JQOjfxFMKLsy4zo6h
"""

# Programme simple pour afficher un message
print("Bonjour, bienvenue en Python !")